openapi: 3.0.0
info:
  version: 1.0.0
  title: Students Rating
  description: An API that allows to see information about students marks, put new marks or post information about new students
  contact:
    email: bogdankalysh20@gmail.com
    name: Bogdan Kalysh

tags:
  - name: user
  - name: group
  - name: subject
  - name: student
  - name: teacher

paths: 
    /user/login:
      get:
        tags:
          - user
        description: autentification of a user
        parameters:
        - name: email
          in: query
          description: The user name for login
          required: true
          schema:
            type: string
        - name: password
          in: query
          description: The password for login in clear text
          required: true
          schema:
            type: string
        responses:
          200:
            description: Logged in
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user'
          400:
            description: Invalid username/password supplied
            
    /user/logout:
      get:
        tags:
          - user
        description: logs out user
        responses:
          default:
            description: successful operation
            
    /user:
      post:
        tags:
          - user
        description: creates a user
        operationId: createUser
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        responses:
          200:
            description: Signed up
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user'
          400:
            description: You didn't fill all fields
        security:
          - student_rating_auth:
            - 'admin:rights'
            
    /user/{id}:
      put:
        tags:
          - user
        description: Update a user
        parameters:
          - in: path 
            name: id
            description: The id of specific user
            required: true
            schema:
              type: integer
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/user'
        responses:
          200:
            description: Sucessfully updated information about the user
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user'
          400:
            description: Wrong ID
            
        security:
          - student_rating_auth:
            - 'admin:rights'       
      delete:
        tags:
        - user
        description: delete a user
        parameters:
        - in: path 
          name: id
          description: The id of specific user
          required: true
          schema:
            type: integer
            
        responses:
          200:
            description: Sucessfully deleted a user
          400:
            description: Wrong ID
            
        security:  
          - student_rating_auth: 
            - 'admin:rights'
            
    /group:
      post:
        tags:
          - group
        description: creates a group
        operationId: createGroup
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/group'
        responses:
          200:
            description: Created student
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/group'
          400:
            description: You didn't fill all fields
        security:
          - student_rating_auth:
            - 'admin:rights'
            
    /group/{id}:
      put:
        tags:
          - group
        description: Update a group
        parameters:
          - in: path 
            name: id
            description: The id of specific group
            required: true
            schema:
              type: integer
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/group'
        responses:
          200:
            description: Sucessfully updated information about the group
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/group'
          400:
            description: Wrong ID
            
        security:
          - student_rating_auth:
            - 'admin:rights'      
      delete:
        tags:
        - group
        description: delete a group
        parameters:
        - in: path 
          name: id
          description: The id of specific group
          required: true
          schema:
            type: integer
            
        responses:
          200:
            description: Sucessfully deleted a group
          400:
            description: Wrong ID
            
        security:  
          - student_rating_auth: 
            - 'admin:rights'
            
            
    /subject:
      post:
        tags:
          - subject
        description: creates a subject
        operationId: createSubject
        requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/subject'
        responses:
          200:
            description: Created student
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/subject'
          400:
            description: You didn't fill all fields
        security:
          - student_rating_auth:
            - 'admin:rights'
            
    /subject/{id}:
      delete:
        tags:
        - subject
        description: delete a subject
        parameters:
        - in: path 
          name: id
          description: The id of specific subject
          required: true
          schema:
            type: integer
            
        responses:
          200:
            description: Sucessfully deleted a subject
          400:
            description: Wrong ID
            
        security:  
          - student_rating_auth: 
            - 'admin:rights'
            
    /students:
      get:
        tags:
          - student
        description: Obtain information about all students
        responses:
          200:
            description: Sucessfully pulled students info
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/user'
          400:
            description: An Error occured
        security:
          - student_rating_auth:
            - 'read:students'
            
    /students/top/{quant}:
      get:
        tags:
          - student
        description: Obtain information about top students
        parameters: 
          - in: path 
            name: quant
            description: Quantity of top students to return
            required: true
            schema:
              type: integer
        responses:
          200:
            description: Sucessfully returned info about top students
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/rating'
          400:
            description: An ERROR occured
        security:
          - student_rating_auth:
            - 'read:students'
            
    /student/{id}:
      get:
        tags:
          - student
        description: Obtain info about specific student
        parameters:
          - in: path
            name: id
            description: The id of specific student
            required: true
            schema:
              type: integer
        responses:
          200:
            description: Sucessfully obtained information about the student
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user'
          400:
            description: Wrong ID
        security:
          - student_rating_auth:
            - 'read:students'
            
    /student/mark:
      post:
        tags:
          - student
        description: put a mark to a student
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mark'
        responses:
          200:
            description: Sucessfully added the mark 
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/mark'
          400:
            description: Wrong ID
      
            
        security:
          - student_rating_auth:
            - 'write:students'
            - 'read:students'
            
    /student/mark/{id}:
      put:
        tags:
          - student
        description: put a mark to a student
        parameters:
          - in: path 
            name: id
            description: The id of specific student
            required: true
            schema:
              type: integer
        requestBody:
          required: true
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/mark'
        responses:
          200:
            description: Sucessfully updated the mark 
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/mark'
          400:
            description: Wrong ID
      
            
        security:
          - student_rating_auth:
            - 'write:students'
            - 'read:students'
      delete:
        tags:
        - student
        description: delete a student
        parameters:
        - in: path 
          name: id
          description: The id of specific mark
          required: true
          schema:
            type: integer
            
        responses:
          200:
            description: Sucessfully deleted the mark
          400:
            description: Wrong ID
            
        security:  
          - student_rating_auth: 
            - 'write:students'
            - 'read:students' 
            
    /teacher/{teacher_id}/add/subject/{subject_id}:
      put:
        tags:
          - teacher
        description: add a subject to a teacher
        parameters:
          - in: path 
            name: subject_id
            description: The id of specific subject
            required: true
            schema:
              type: integer
          - in: path 
            name: teacher_id
            description: The id of specific subject
            required: true
            schema:
              type: integer
        responses:
          200:
            description: Sucessfully added the mark 
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user'
          400:
            description: Wrong ID
            
        security:
          - student_rating_auth:
            - 'admin:rights'
            
    /teacher/{teacher_id}/add/group/{group_id}:
      put:
        tags:
          - teacher
        description: add a group to a teacher
        parameters:
          - in: path 
            name: teacher_id
            description: The id of specific group
            required: true
            schema:
              type: integer
          - in: path 
            name: group_id
            description: The id of specific group
            required: true
            schema:
              type: integer
        responses:
          200:
            description: Sucessfully added the group
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/user'
          400:
            description: Wrong ID
            
        security:
          - student_rating_auth:
            - 'admin:rights'
            
            
components:
  schemas:
    user:
      type: object
      
      description: Model containing user info
      properties:
        id:
          type: integer
                        
        name:
          type: string
                        
        email:
          type: string
          
        password:
          type: string
          
        type_of_user:
          type: string
          
        group_id:
          type: integer
            
    mark:
      type: object
      
      description: Model containing mark info
      properties:
        id:
          type: integer
        date:
          type: number
        mark:
          type: integer
        subject_id:
          type: integer
        student_id:
          type: integer
              
    rating:
      type: object
      
      description: Model containing students rating info
      properties:
        student_id:
          type: integer
        name:
          type: string
        group:
          type: string
        mark:
          type: integer
          
    group:
      type: object
      
      description: Model containing group info
      properties:
        student_id:
          type: integer
        name:
          type: string
          
    subject:
      type: object
      
      description: Model containing subject info
      properties:
        student_id:
          type: integer
        name:
          type: string

  securitySchemes:
    student_rating_auth:
      type: oauth2
      flows:
        implicit:
          authorizationUrl: 'http://student.rating.io/oauth/dialog'
          scopes:
            'write:students': modify students info
            'read:students': read info about students
            'admin:rights': read info about students